/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AutoInsuranceRequest } from '../../models/offer/auto-insurance-request';
import { QuoteResponse } from '../../models/offer/quote-response';

export interface Calculate$Params {
      body: AutoInsuranceRequest
}

export function calculate(http: HttpClient, rootUrl: string, params: Calculate$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteResponse>> {
  const rb = new RequestBuilder(rootUrl, calculate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuoteResponse>;
    })
  );
}

calculate.PATH = '/api/v1/automobile/calculate';
