/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Offer } from '../../models/offer';

export interface GetOfferById$Params {
  id: string;
}

export function getOfferById(http: HttpClient, rootUrl: string, params: GetOfferById$Params, context?: HttpContext): Observable<StrictHttpResponse<Offer>> {
  const rb = new RequestBuilder(rootUrl, getOfferById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Offer>;
    })
  );
}

getOfferById.PATH = '/api/v1/offers/{id}';
