/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OfferWithTagsResponse } from '../../models/offer-with-tags-response';

export interface GetAllByCategoryId$Params {
  categoryId: string;
}

export function getAllByCategoryId(http: HttpClient, rootUrl: string, params: GetAllByCategoryId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OfferWithTagsResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllByCategoryId.PATH, 'get');
  if (params) {
    rb.path('categoryId', params.categoryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OfferWithTagsResponse>>;
    })
  );
}

getAllByCategoryId.PATH = '/api/v1/offers/getAllByCategoryId/{categoryId}';
