/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VehicleInfo } from '../../models/offer/vehicle-info';

export interface GetVehicleInfo1$Params {
  vin: string;
}

export function getVehicleInfo1(http: HttpClient, rootUrl: string, params: GetVehicleInfo1$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleInfo>> {
  const rb = new RequestBuilder(rootUrl, getVehicleInfo1.PATH, 'get');
  if (params) {
    rb.path('vin', params.vin, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VehicleInfo>;
    })
  );
}

getVehicleInfo1.PATH = '/api/v1/VINDecoder/decode/{vin}';
