/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OfferResponse } from '../../models/offer-response';

export interface GetOne$Params {
}

export function getOne(http: HttpClient, rootUrl: string, params?: GetOne$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferResponse>> {
  const rb = new RequestBuilder(rootUrl, getOne.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OfferResponse>;
    })
  );
}

getOne.PATH = '/api/v1/offers/one';
