/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Offer } from '../../models/offer';

export interface UpdateOffer$Params {
  id: string;
      body: Offer
}

export function updateOffer(http: HttpClient, rootUrl: string, params: UpdateOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<Offer>> {
  const rb = new RequestBuilder(rootUrl, updateOffer.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Offer>;
    })
  );
}

updateOffer.PATH = '/api/v1/offers/{id}';
