/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { OfferControllerService } from './services/offer-controller.service';
export { OfferCategoryControllerService } from './services/offer-category-controller.service';


