/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { HealthQuoteControllerService } from './services/health-quote-controller.service';
export { AutomobileQuoteControllerService } from './services/automobile-quote-controller.service';
export { TestControllerService } from './services/test-controller.service';
