/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../../base-service';
import { ApiConfiguration } from '../../api-configuration';
import { StrictHttpResponse } from '../../strict-http-response';

import { calculate } from '../../fn/automobile-quote-controller/calculate';
import { Calculate$Params } from '../../fn/automobile-quote-controller/calculate';
import { QuoteResponse } from '../../models/offer/quote-response';

@Injectable({ providedIn: 'root' })
export class AutomobileQuoteControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `calculate()` */
  static readonly CalculatePath = '/api/v1/automobile/calculate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `calculate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  calculate$Response(params: Calculate$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteResponse>> {
    return calculate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `calculate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  calculate(params: Calculate$Params, context?: HttpContext): Observable<QuoteResponse> {
    return this.calculate$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuoteResponse>): QuoteResponse => r.body)
    );
  }

}
