/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../../base-service';
import { ApiConfiguration } from '../../api-configuration';
import { StrictHttpResponse } from '../../strict-http-response';

import { CategoryResponse } from '../../models';
import { createOfferCategory } from '../../fn/offer-category-controller/create-offer-category';
import { CreateOfferCategory$Params } from '../../fn/offer-category-controller/create-offer-category';
import { deleteOfferCategory } from '../../fn/offer-category-controller/delete-offer-category';
import { DeleteOfferCategory$Params } from '../../fn/offer-category-controller/delete-offer-category';
import { getAll1 } from '../../fn/offer-category-controller/get-all-1';
import { GetAll1$Params } from '../../fn/offer-category-controller/get-all-1';
import { getAllByTarget } from '../../fn/offer-category-controller/get-all-by-target';
import { GetAllByTarget$Params } from '../../fn/offer-category-controller/get-all-by-target';
import { getOfferCategoryById } from '../../fn/offer-category-controller/get-offer-category-by-id';
import { GetOfferCategoryById$Params } from '../../fn/offer-category-controller/get-offer-category-by-id';
import { updateOfferCategory } from '../../fn/offer-category-controller/update-offer-category';
import { UpdateOfferCategory$Params } from '../../fn/offer-category-controller/update-offer-category';

@Injectable({ providedIn: 'root' })
export class OfferCategoryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateOfferCategory()` */
  static readonly UpdateOfferCategoryPath = '/api/v1/offer-categories/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOfferCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOfferCategory$Response(params: UpdateOfferCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponse>> {
    return updateOfferCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOfferCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOfferCategory(params: UpdateOfferCategory$Params, context?: HttpContext): Observable<CategoryResponse> {
    return this.updateOfferCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body)
    );
  }

  /** Path part for operation `createOfferCategory()` */
  static readonly CreateOfferCategoryPath = '/api/v1/offer-categories/create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOfferCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOfferCategory$Response(params: CreateOfferCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponse>> {
    return createOfferCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOfferCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOfferCategory(params: CreateOfferCategory$Params, context?: HttpContext): Observable<CategoryResponse> {
    return this.createOfferCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body)
    );
  }

  /** Path part for operation `getOfferCategoryById()` */
  static readonly GetOfferCategoryByIdPath = '/api/v1/offer-categories/getOne/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOfferCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOfferCategoryById$Response(params: GetOfferCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponse>> {
    return getOfferCategoryById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOfferCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOfferCategoryById(params: GetOfferCategoryById$Params, context?: HttpContext): Observable<CategoryResponse> {
    return this.getOfferCategoryById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body)
    );
  }

  /** Path part for operation `getAll1()` */
  static readonly GetAll1Path = '/api/v1/offer-categories/getAll';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll1$Response(params?: GetAll1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryResponse>>> {
    return getAll1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll1(params?: GetAll1$Params, context?: HttpContext): Observable<Array<CategoryResponse>> {
    return this.getAll1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CategoryResponse>>): Array<CategoryResponse> => r.body)
    );
  }

  /** Path part for operation `getAllByTarget()` */
  static readonly GetAllByTargetPath = '/api/v1/offer-categories/getAllByTarget/{target}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllByTarget()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllByTarget$Response(params: GetAllByTarget$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryResponse>>> {
    return getAllByTarget(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllByTarget$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllByTarget(params: GetAllByTarget$Params, context?: HttpContext): Observable<Array<CategoryResponse>> {
    return this.getAllByTarget$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CategoryResponse>>): Array<CategoryResponse> => r.body)
    );
  }

  /** Path part for operation `deleteOfferCategory()` */
  static readonly DeleteOfferCategoryPath = '/api/v1/offer-categories/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOfferCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOfferCategory$Response(params: DeleteOfferCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteOfferCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOfferCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOfferCategory(params: DeleteOfferCategory$Params, context?: HttpContext): Observable<void> {
    return this.deleteOfferCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
