/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AutomobileDto } from '../models/automobile-dto';
import { GeneratedQuoteDto } from '../models/generated-quote-dto';
export interface AppointmentDto {
  cin?: number;
  dob?: string;
  email?: string;
  firstName?: string;
  generatedQuote?: GeneratedQuoteDto;
  lastName?: string;
  offerDetails?: AutomobileDto;
  offerType?: 'AUTO' | 'HEALTH';
  phone?: number;
}
