/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocationDto } from '../models/location-dto';
export interface AutomobileDto {
  accidentHistory?: string;
  addressInfo?: LocationDto;
  billingPeriod?: string;
  coverageType?: string;
  defensiveDrivingCourse?: boolean;
  drivingExperience?: number;
  licenseNumber?: string;
  trafficViolations?: boolean;
  vehicleMake?: string;
  vehicleModel?: string;
  vehicleType?: string;
  vin?: string;
}
