/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FilteredCategory {
  categoryId?: string;
  categoryTarget?: string;
  name?: string;
}
