/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BoundingBox } from '../models/bounding-box';
export interface LocationDto {
  boundingBox?: BoundingBox;
  country?: string;
  countryCode?: string;
  countryCodeISO3?: string;
  countrySubdivision?: string;
  countrySubdivisionCode?: string;
  countrySubdivisionName?: string;
  extendedPostalCode?: string;
  freeformAddress?: string;
  localName?: string;
  municipality?: string;
  postalCode?: string;
  streetName?: string;
  streetNumber?: string;
}
