/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilteredCategory } from '../models/filtered-category';
import { OfferLabel } from '../models/offer-label';
export interface Offer {
  active?: boolean;
  category?: FilteredCategory;
  createdAt?: string;
  header?: string;
  imageUri?: string;
  labels?: Array<OfferLabel>;
  name?: string;
  offerId?: string;
}
