/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnswersTypeDto } from '../models/answers-type-dto';
import { QuestionTypeDto } from '../models/question-type-dto';
export interface OfferLabelDto {
  answers?: Array<AnswersTypeDto>;
  name: string;
  questions?: Array<QuestionTypeDto>;
}
