/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BenefitTypeDto } from '../models/benefit-type-dto';
import { FilteredCategoryDto } from '../models/filtered-category-dto';
import { OfferLabelDto } from '../models/offer-label-dto';
import { OfferPackageDto } from '../models/offer-package-dto';
export interface OfferResponse {
  benefits?: Array<BenefitTypeDto>;
  category?: FilteredCategoryDto;
  header?: string;
  imageUri?: string;
  labels?: Array<OfferLabelDto>;
  name?: string;
  offerId?: string;
  packages?: Array<OfferPackageDto>;
}
