/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OfferCategory } from '../models/offer-category';
export interface Offer {
  active?: boolean;
  description?: string;
  name?: string;
  offerCategory?: OfferCategory;
  offerId?: string;
  premium?: number;
  validity?: string;
}
