/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryRequest {
  categoryTarget?: 'PARTICULAR' | 'COMPANY';
  description?: string;
  imageUri?: string;
  name?: string;
}
