/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HealthInsuranceRequest {
  addOns?: Array<string>;
  age?: number;
  alcohol?: string;
  bmi?: number;
  chronicIllnesses?: string;
  deductible?: number;
  employerInsurance?: string;
  exercise?: string;
  existingInsurance?: string;
  familyHistory?: Array<string>;
  gdprConsent?: boolean;
  gender?: string;
  governorate?: string;
  hospitalizations?: string;
  medications?: string;
  occupation?: string;
  planType?: string;
  preExistingConditions?: Array<string>;
  smoking?: string;
  surgeries?: string;
  travelFrequency?: string;
  vaccinations?: Array<string>;
}
