/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferCategory {
  createdAt?: string;
  description?: string;
  imageUri?: string;
  name?: string;
  offerCategoryId?: string;
}
