/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchasedOfferData {
  fieldLabel?: string;
  fieldType?: string;
  fieldValue?: any;
}
