/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuoteResponse {
  amount?: number;
  baseAnnualPremium?: number;
  billingPeriod?: 'MONTHLY' | 'QUARTERLY' | 'SEMI_ANNUAL' | 'ANNUAL';
  currency?: string;
  validFrom?: string;
  validTo?: string;
}
