/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VehicleInfo {
  abs?: string;
  backupCamera?: string;
  bodyClass?: string;
  daytimeRunningLights?: string;
  displacementL?: string;
  doors?: string;
  electronicStabilityControl?: string;
  fuelTypePrimary?: string;
  grossVehicleWeightRating?: string;
  make?: string;
  model?: string;
  modelYear?: string;
  plantCountry?: string;
  seatingCapacity?: string;
  tractionControl?: string;
  vehicleType?: string;
  vin?: string;
}
