/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WhoData {
  Dim1?: string;
  Dim1Type?: string;
  High?: number;
  IndicatorCode?: string;
  Low?: number;
  NumericValue?: number;
  SpatialDim?: string;
  SpatialDimType?: string;
  TimeDim?: number;
  TimeDimType?: string;
  TimeDimensionValue?: string;
}
