/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WhoData } from '../models/who-data';
export interface WhoApiResponse {
  value?: Array<WhoData>;
}
