/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createOffer } from '../fn/offer-controller/create-offer';
import { CreateOffer$Params } from '../fn/offer-controller/create-offer';
import { Offer } from '../models/offer';

@Injectable({ providedIn: 'root' })
export class OfferControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createOffer()` */
  static readonly CreateOfferPath = '/api/v1/offers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOffer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOffer$Response(params: CreateOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<Offer>> {
    return createOffer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOffer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOffer(params: CreateOffer$Params, context?: HttpContext): Observable<Offer> {
    return this.createOffer$Response(params, context).pipe(
      map((r: StrictHttpResponse<Offer>): Offer => r.body)
    );
  }

}
