import { AutomobileDto } from './automobile-dto';
import { GeneratedQuoteDto } from './generated-quote-dto';
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AppointmentDto {
  cin?: number;
  dob?: string;
  email?: string;
  firstName?: string;
  generatedQuote?: GeneratedQuoteDto;
  lastName?: string;
  offerDetails?: AutomobileDto;
  offerType?: 'AUTO' | 'HEALTH';
  phone?: number;
}
