/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeneratedQuoteDto {
  amount?: number;
  baseAnnualPremium?: number;
  billingPeriod?: string;
  currency?: string;
  validFrom?: string;
  validTo?: string;
}
