/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferDeletionRequest {
  formId?: string;
  isForm?: boolean;
  isOffer?: boolean;
  isPurchasedOffers?: boolean;
  offerId?: string;
}
