/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferPackageDto {
  customDuration?: string;
  duration?: string;
  features?: Array<string>;
  price?: number;
  title?: string;
}
