/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FormFieldDto } from './form-field-dto';
export interface OfferFormResponse {
  fields?: Array<FormFieldDto>;
  formId?: string;
}
