/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchasedOfferDataDto } from '../models/purchased-offer-data-dto';
export interface PurchasedOfferRequest {
  data?: Array<PurchasedOfferDataDto>;
  formId?: string;
  offerId?: string;
}
