/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnswersType } from '../models/answers-type';
export interface OfferLabel {
  answers?: Array<AnswersType>;
  name?: string;
  questions?: Array<string>;
}
