/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilteredCategoryDto } from '../models/filtered-category-dto';
import { OfferLabelDto } from '../models/offer-label-dto';
export interface OfferRequest {
  category: FilteredCategoryDto;
  header: string;
  imageUri?: string;
  labels?: Array<OfferLabelDto>;
  name: string;
}
