/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { calculateHealth } from '../fn/health-quote-controller/calculate-health';
import { CalculateHealth$Params } from '../fn/health-quote-controller/calculate-health';
import { QuoteResponse } from '../models/quote-response';

@Injectable({ providedIn: 'root' })
export class HealthQuoteControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `calculateHealth()` */
  static readonly CalculateHealthPath = '/api/v1/health/calculate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `calculateHealth()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  calculateHealth$Response(params: CalculateHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<QuoteResponse>> {
    return calculateHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `calculateHealth$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  calculateHealth(params: CalculateHealth$Params, context?: HttpContext): Observable<QuoteResponse> {
    return this.calculateHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<QuoteResponse>): QuoteResponse => r.body)
    );
  }

}
