/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getVehicleInfo } from '../fn/test-controller/get-vehicle-info';
import { GetVehicleInfo$Params } from '../fn/test-controller/get-vehicle-info';
import { getWhoStats } from '../fn/test-controller/get-who-stats';
import { GetWhoStats$Params } from '../fn/test-controller/get-who-stats';
import { VehicleInfo } from '../models/vehicle-info';
import { WhoApiResponse } from '../models/who-api-response';

@Injectable({ providedIn: 'root' })
export class TestControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getWhoStats()` */
  static readonly GetWhoStatsPath = '/api/v1/test/who';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWhoStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWhoStats$Response(params?: GetWhoStats$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WhoApiResponse>>> {
    return getWhoStats(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWhoStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWhoStats(params?: GetWhoStats$Params, context?: HttpContext): Observable<Array<WhoApiResponse>> {
    return this.getWhoStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<WhoApiResponse>>): Array<WhoApiResponse> => r.body)
    );
  }

  /** Path part for operation `getVehicleInfo()` */
  static readonly GetVehicleInfoPath = '/api/v1/test/decode/{vin}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVehicleInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVehicleInfo$Response(params: GetVehicleInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleInfo>> {
    return getVehicleInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVehicleInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVehicleInfo(params: GetVehicleInfo$Params, context?: HttpContext): Observable<VehicleInfo> {
    return this.getVehicleInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<VehicleInfo>): VehicleInfo => r.body)
    );
  }

}
