/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getVehicleInfo } from '../fn/vin-decoder-controller/get-vehicle-info';
import { GetVehicleInfo$Params } from '../fn/vin-decoder-controller/get-vehicle-info';
import { VehicleInfo } from '../models/vehicle-info';

@Injectable({ providedIn: 'root' })
export class VinDecoderControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getVehicleInfo()` */
  static readonly GetVehicleInfoPath = '/api/v1/VINDecoder/decode/{vin}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVehicleInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVehicleInfo$Response(params: GetVehicleInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<VehicleInfo>> {
    return getVehicleInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVehicleInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVehicleInfo(params: GetVehicleInfo$Params, context?: HttpContext): Observable<VehicleInfo> {
    return this.getVehicleInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<VehicleInfo>): VehicleInfo => r.body)
    );
  }

}
