/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResponse } from '../../models/offer/category-response';

export interface GetAllByTarget$Params {
  target: 'PARTICULAR' | 'COMPANY';
}

export function getAllByTarget(http: HttpClient, rootUrl: string, params: GetAllByTarget$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllByTarget.PATH, 'get');
  if (params) {
    rb.path('target', params.target, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoryResponse>>;
    })
  );
}

getAllByTarget.PATH = '/api/v1/offer-categories/getAllByTarget/{target}';
