/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeneratedQuoteDto } from './generated-quote-dto';
export interface AppointmentDto {
  appointmentId?: number;
  cin?: number;
  dob?: string;
  email?: string;
  firstName?: string;
  generatedQuote?: GeneratedQuoteDto;
  lastName?: string;
  offerDetails?: any;
  offerType?: 'AUTO' | 'HEALTH';
  phone?: number;
}
