/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Position } from '../models/position';
export interface BoundingBox {
  entity?: string;
  northEast?: Position;
  southWest?: Position;
}
