/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponse {
  categoryId?: string;
  categoryTarget?: 'PARTICULAR' | 'COMPANY';
  createdAt?: string;
  description?: string;
  imageUri?: string;
  name?: string;
}
