/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeoWeatherData {
  averageMaxTmp?: number;
  averageMinTmp?: number;
  averagePrecipitation?: number;
  averageWind?: number;
  isUrbanArea?: boolean;
}
