/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferWithTagsResponse {
  category?: string;
  imageUri?: string;
  name?: string;
  offerId?: string;
  tags?: Array<string>;
}
