
/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchasedOfferData } from "./purchased-offer-data";


export interface PurchasedOffer {
  data?: Array<PurchasedOfferData>;
  formId?: string;
  offerId?: string;
  purchasedOfferId?: string;
  userId?: string;
}
